docker commands:

sudo docker build -t imagename .
sudo docker run -it -d -p 8080:8080 imagename
curl localhost:8080

sudo docker container stop ac(container id 2 letters)
sudo docker container ps
sudo docker images
--------------
helm:

fb-sdova-ecsm-dev
fb-sdovb-scm-dev
fb-dxt1-scm-dev

------
dockerfile:

fb-sdova-ecscm-devops
fb-sdovb-scm-dev
fb-dxt1-scm-dev

------
fb-sp2k-scm-171 - dev and qa changes
fb-scm-sp2k-qa

-------------------------------
Dockerfile example:

# node Base image with latest
FROM node:latest
 
# Adding application specific group and user
RUN groupadd -g 999 sdova-grp && useradd -r -u 999 -g root sdova
 
# Creating app directory and switching
WORKDIR /app
 
# Copying package.json to app directory ---{package*.json ./}
COPY package.json .
 
# Installing the dependency node modules
RUN npm install
 
# Copying application code to app directory {bundle all app code inside docker image}
COPY . .
 
# Building the application
RUN npm run build
 
# Changing the user and/or group ownership of an app directory
RUN chown sdova:sdova-grp /app -R
 
EXPOSE 8080
 
# Switching user to application user from root
USER sdova
 
# Running the application
CMD [ "node", "server.js" ]


--------------------------------

FROM node:14
WORKDIR /usr/src/app
COPY package*.json app.js ./
RUN npm install
EXPOSE 3000
CMD ["node", "app.js"]

--------------------
sp2k - Dockerfile

# Ubuntu Base image with openjdk8 
FROM escoacrprod01.azurecr.io/ubuntu/tomee/openjdk8:8.0.x 

# Adding application specific group and user 
RUN groupadd -g 999 sp2k-grp && useradd -r -u 999 -g root sp2k 

COPY setenv.sh /usr/local/tomee/bin/

# Creating app directory 
RUN mkdir /app 

# Copying application jar to app directory 
COPY target/*.ear /app 


WORKDIR /app
 
# Changing the user and/or group ownership of an app directory 
RUN chown sp2k:sp2k-grp /app -R 
RUN chown sp2k:sp2k-grp /usr/local/tomee/ -R


# Exposing the container port 
EXPOSE 8080 

# Switching user to application user from root 
USER sp2k

# Starting the service
# ENTRYPOINT ["java", "-jar", "/app/sp2k.ear"]
CMD /usr/local/tomee/bin/catalina.sh run

---------------------------------------------------

sdova-ui-angular/dockerfile at fb-sdova-ecscm-devops · albertsons/sdova-ui-angular

----------------
sdovb and megn -- java docker file

# Ubuntu Base image with openjdk8
FROM escoacrprod01.azurecr.io/ubuntu/openjdk:1.8
 
# Adding application specific group and user
RUN groupadd -g 999 sdovb-grp && useradd -r -u 999 -g root sdovb
 
# Creating app directory
RUN mkdir /usr/src/app
 
# Copying application jar to app directory
COPY target/*.jar /usr/src/app
 
# Changing the user and/or group ownership of an app directory
RUN chown sdovb:sdovb-grp /usr/src/app -R
 
# Exposing the container port
EXPOSE 8080
 
# Switching user to application user from root
USER sdovb
 
# Running the application jar as an entry point
ENTRYPOINT ["java", "-jar", "/usr/src/app/dino-octopus-recipe-1.0.local.jar"]